### ISSUE TITLE
Explicar como funciona github

### ISSUE THREAD

**Issue by G00Z-G00Z** [equipo-lab-control/proyecto-1#1]
Explicarles como subir archivos a github y como lo podemos organizar

**Comment by G00Z-G00Z** [comment]
@Vex4444 @AOEli @CharlyReyes5 
Porfavor vean el vídeo que les mande por wa para usar github 
Sí ven este mensaje, comenten en este issue pls

**Comment by CharlyReyes5** [comment]
Va hoy veo el video
