### ISSUE TITLE
Explicar pasos de el PID y la función deseada

### ISSUE THREAD

**Issue by AOEli** [equipo-lab-control/proyecto-1#25]
Se deben indicar qué son las variables mostradas en las slides de la etapa 3 y hay que mostrar cómo se obtuvo el modelo en tiempo discreto y el código (c2d)

**Comment by G00Z-G00Z** [comment]
@AOEli Si crees que sea necesario explicar como sacar el discreto? O solamente pongo que maltab lo hace por nosotros

@Vex4444 Tienes como sacamos el modelo discreto del PID?

**Comment by AOEli** [comment]
@G00Z-G00Z Pues pienso que a lo mejor convendría ponerlo, es de que no recuerdo muy bien cómo nos fue en esa parte. Si nos bajó muchos puntos supongo que igual valdría la pena ponerlo.

**Comment by G00Z-G00Z** [comment]
Ya quedó, pero comoquiera puse que en matlab se hacía de manera automática
